version: "3.8"

services:
  backend:
    build:
      target: development
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
  frontend:
    build:
      target: development
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  markets-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - markets-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  redis:
    image: redis:alpine
    command: redis-server
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
volumes:
  postgres-db:
  markets-db:
  redis-data:
  redis-conf:

