apiVersion: v1
kind: Service
metadata:
  name: bifrost-frontend-service
  namespace: bifrost-testing
spec:
  type: NodePort
  selector:
    app: bifrost-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
